version: '3'

services:
    web:
        image: nginx:alpine
        ports:
            - ${FRONTEND_PORT}:80
            - ${BACKEND_PORT}:81
        volumes:
            - .:/app
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - .:/app
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/docker.ini
        user: 1000:1000

    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_DATABASE=test
        volumes:
            - mysql:/var/lib/mysql
            - .:/app
        ports:
            - ${MYSQL_PORT}:3306

volumes:
    mysql: {}